build:
  phpunit:
    image: daothaison/civ3-workspace:latest
    commands:
    - composer install
    - echo done
    - sleep 3
    - framgia-ci run
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
  mysql_test:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead_test
      MYSQL_USER: homestead_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
cache:
  mount:
    - .git
    - vendor
    - node_modules
deploy:
  docker:
    username: octocat
    password: password
    email: dangminhtruong@gmail.com
    repo: dangminhtruong/Havana_Laravel
project_type: php
test:
  eslint:
    ignore: false
    command: eslint --format=checkstyle
      --output-file=.framgia-ci-reports/eslint.xml
      resources/assets/js/ --ext .js
  phpcs:
    ignore: false
    command: echo '' | phpcs --standard=Framgia --report-checkstyle=.framgia-ci-reports/phpcs.xml --ignore=app/Supports/* app
  phpunit:
    ignore: false
    command:
      - php -dzend_extension=xdebug.so vendor/bin/phpunit
        --coverage-clover=.framgia-ci-reports/coverage-clover.xml
        --coverage-html=.framgia-ci-reports/coverage
